apiVersion: apps/v1
kind: Deployment
metadata:
  name: web 
spec:
  replicas: 3 
  selector: 
    matchLabels: 
      app: web 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%    
  template:
      metadata:
        name: web
        labels:
          app: web
      spec:
        containers:
        - name: web
          image: doped/nginx-without-su:latest
          livenessProbe:
            tcpSocket: 
               port: 8000
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8000         
          volumeMounts:
          - name: app
            mountPath: /app
        initContainers:
        - name: init-web
          image: busybox:1.31.0
          volumeMounts:
          - name: app
            mountPath: /app
          command: ['sh', '-c', 'wget -O- --no-check-certificate https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
        volumes:
        - name: app
          emptyDir: {}
