apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: doped/nginx-without-su:latest
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:        
    - name: init
      image: busybox:1.31.0
      volumeMounts:
        - name: app
          mountPath: /app
      command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
  volumes:
    - name: app
      emptyDir: {}
